version: 2.0
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - prealloc
    - unconvert
    - gocritic
  fast: false

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    severity: medium
    confidence: medium
  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-dirs:
    - bin
    - scripts
    - migrations
  exclude-rules:
    - path: ^.*_test\.go$
      linters:
        - gosec
